import type { Icon } from "@phosphor-icons/react";
import {
  BathtubIcon,
  BoneIcon,
  BridgeIcon,
  BusIcon,
  CarIcon,
  ClockIcon,
  BowlFoodIcon,
  BugIcon,
  ClipboardTextIcon,
  CatIcon,
  DogIcon,
  DropIcon,
  EarIcon,
  EyeIcon,
  FirstAidIcon,
  FlaskIcon,
  HeartbeatIcon,
  LockIcon,
  MapPinIcon,
  MapTrifoldIcon,
  MicroscopeIcon,
  MoonIcon,
  PathIcon,
  PawPrintIcon,
  PersonSimpleWalkIcon,
  PillIcon,
  ScalesIcon,
  ScanIcon,
  ScissorsIcon,
  ShieldCheckIcon,
  StethoscopeIcon,
  StorefrontIcon,
  SyringeIcon,
  TestTubeIcon,
  ToothIcon,
  TreeIcon,
  WarningCircleIcon,
  WalletIcon,
  WaveformIcon,
  WindIcon,
} from "@phosphor-icons/react/dist/ssr";

/**
 * O conteúdo (content/paginas.ts) guarda só o NOME do ícone, para a copy não
 * depender de import de componente. O mapa mora aqui, do lado do layout.
 */
const mapa: Record<string, Icon> = {
  bath: BathtubIcon,
  bone: BoneIcon,
  bridge: BridgeIcon,
  bus: BusIcon,
  car: CarIcon,
  clock: ClockIcon,
  bowl: BowlFoodIcon,
  bug: BugIcon,
  cat: CatIcon,
  clipboard: ClipboardTextIcon,
  dog: DogIcon,
  drop: DropIcon,
  ear: EarIcon,
  eye: EyeIcon,
  firstAid: FirstAidIcon,
  flask: FlaskIcon,
  heartbeat: HeartbeatIcon,
  lock: LockIcon,
  map: MapTrifoldIcon,
  mapPin: MapPinIcon,
  microscope: MicroscopeIcon,
  moon: MoonIcon,
  path: PathIcon,
  paw: PawPrintIcon,
  walk: PersonSimpleWalkIcon,
  pill: PillIcon,
  scales: ScalesIcon,
  scan: ScanIcon,
  scissors: ScissorsIcon,
  shield: ShieldCheckIcon,
  stethoscope: StethoscopeIcon,
  store: StorefrontIcon,
  syringe: SyringeIcon,
  testTube: TestTubeIcon,
  tooth: ToothIcon,
  tree: TreeIcon,
  warning: WarningCircleIcon,
  wallet: WalletIcon,
  waveform: WaveformIcon,
  wind: WindIcon,
};

export function Icone({ nome, tamanho = 22 }: { nome?: string; tamanho?: number }) {
  const Componente = (nome && mapa[nome]) || PawPrintIcon;
  return <Componente size={tamanho} weight="light" aria-hidden />;
}
